name: Generate Table of Contents

on:
  push:
    branches:
      - '**' # Trigger on push to any branch

jobs:
  generate-toc:
    name: Generate Markdown TOC
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install and run gh-md-toc to generate TOC
      - name: Install gh-md-toc
        run: |
          sudo curl -s https://raw.githubusercontent.com/ekalinin/github-markdown-toc/master/gh-md-toc -o /usr/local/bin/gh-md-toc
          sudo chmod +x /usr/local/bin/gh-md-toc

      - name: Generate TOC for Markdown files
        run: |
          for file in $(find . -name "*.md"); do
            gh-md-toc --insert "$file"
          done

      # Commit and push changes back to the branch
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore: Update TOC in Markdown files"
          git push
        env:
          # Provide the GitHub token for authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
